name: experiments
on: 
  pull_request:
    branches:
      - experiments
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python Env Setup
        run: |
          pip install pipenv
          pipenv sync
      - name: Retrain model
        run: |
          # Your ML workflow goes here
          pipenv run python Models/model/train.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Retrain Model Metrics" >> report.md
          cat Models/model/Assests/metrics.md >> report.md
          echo "## Retrain Model Confusion Metix" >> report.md
          cml-publish Model/model/Assests/confusion_matrix.png --md >> report.md
          cml send-comment report.md
